### ISSUE TITLE
errmsg - maximum bytes of RAM.

### ISSUE THREAD

**Issue by Amarounek** [mikeckennedy/mongodb-for-python-developers#10]
Hello,

I am sorry if I am asking the question on the wrong page, however I didn't find any email contact or another form in your course.

My issue is that Robomongo has raised the error after this code:
`db.Book.find({}, {Title:1, Published: 1}).sort({Published: -1})`

With this:
```
Error: error: {
	"ok" : 0,
	"errmsg" : "Executor error during find command :: caused by :: Sort operation used more than the maximum 100302864 bytes of RAM. Add an index, or specify a smaller limit.",
	"code" : 96,
	"codeName" : "OperationFailed"
}
```

I found it that it is the problem with the authorization of admin user, however, I am not sure how to solve it properly.

Thx for help!

**Comment by mikeckennedy** [comment]
Hi @Amarounek, 

The problem is you need an index to sort large amounts of data:

```
Sort operation used more than the maximum 100302864 bytes of RAM. Add an index
```

So add an index for `Published` and you'll be good.
