### ISSUE TITLE
Robomongo name change

### ISSUE THREAD

**Issue by jchenj** [mikeckennedy/mongodb-for-python-developers#11]
In March 2017 Robomongo was renamed Robo 3T after acquisition by 3T. 

[https://blog.robomongo.org/changing-the-name-of-robomongo/](https://blog.robomongo.org/changing-the-name-of-robomongo/)

It would be helpful to say which product is appropriate/best to use in the course, Studio 3T or Robo 3T:
[https://robomongo.org/](https://robomongo.org/)

**Comment by mikeckennedy** [comment]
Hi @jchenj Robo 3T is definitely the one we use in the course. MongoDB has Compass as well. I would think all three would be fine. Also, PyCharm pro has MongoDB DB integration included these days too. But I love Robo 3T and use it during the course too. :)

**Comment by jchenj** [comment]
Thanks for the clarification, @mikeckennedy! Really enjoying the course & appreciate all of your work! :)

**Comment by mikeckennedy** [comment]
Thank you Julianna! :)
