### ISSUE TITLE
Some commands are deprecated

### ISSUE THREAD

**Issue by mikeckennedy** [mikeckennedy/mongodb-for-python-developers#9]
Things like update() -> update_one(), insert() -> insert_one().

**Comment by jchenj** [comment]
count() is another deprecated command. 

````
/Users/jchen/Desktop/Courses/MongoDB-Python/mongodb-for-python-developers/
src/05_pymongo/play_around_pymongo/program.py: 
DeprecationWarning: count is deprecated. Use estimated_document_count 
or count_documents instead....

if db.books.count() == 0:
````
count() can be replaced by [estimated_document_count()](https://api.mongodb.com/python/current/api/pymongo/collection.html#pymongo.collection.Collection.estimated_document_count) for fast count of total docs in collection.

**Comment by mikeckennedy** [comment]
Thank you @jchenj I just updated the code here to use the newer version. :)
